@baseUrl = http://localhost:3333
#@accessToken = {{autenthenticate.response.body.access_token}}

# @name autenthenticate_courier
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "courier@fastfeet.com",
  "password": "123456"
}

###

# @name autenthenticate_admin
POST {{baseUrl}}/admins/sessions
Content-Type: application/json

{
  "email": "admin@fastfeet.com",
  "password": "123456"
}