services:
  postgres:
    container_name: fast-feet-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fast-feet
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    
  cache:
    container_name: fast-feet-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
